# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          HACKSY.IO
paginate:       5
baseurl:        ""
url:            "https://greghxc.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Greg Mertzlufft
  url:          http://hacksy.io
  email:        greg@hacksy.io

# Custom vars
version:        0.0.1
github:
  repo:         https://github.com/greghxc/greghxc.github.io

# Gems
gems:
  - jekyll-paginate

excerpt_separator: <!--more-->
